
-- INSERINDO PESSOAS
INSERT INTO PESSOA(ID_PESSOA, NOME, SOBRENOME, EMAIL) VALUES (1, 'Bruno', 'Carneiro', 'bruno.carneiro312@gmail.com');
INSERT INTO PESSOA(ID_PESSOA, NOME, SOBRENOME, EMAIL) VALUES (2, 'Thiago', 'Carneiro', 'gothya@gmail.com');
INSERT INTO PESSOA(ID_PESSOA, NOME, SOBRENOME, EMAIL) VALUES (3, 'Sarah', 'Carneiro', 'sarahsfcarneiro@gmail.com');

-- INSERINDO ENDEREÇOS
INSERT INTO ENDERECO(ID_ENDERECO, CEP, LOGRADOURO, BAIRRO, CIDADE, UF, COMPLEMENTO) VALUES (1, '70765110', 'sqn 312 bl k', 'Asa Norte', 'Brasília', 'DF', 'apto 102');

-- ASSOCIANDO PESSOAS A ENDEREÇOS
INSERT INTO PESSOA_ENDERECO (ID_ENDERECO, ID_PESSOA) VALUES (1, 1);
INSERT INTO PESSOA_ENDERECO (ID_ENDERECO, ID_PESSOA) VALUES (1, 2);
INSERT INTO PESSOA_ENDERECO (ID_ENDERECO, ID_PESSOA) VALUES (1, 3);